name: Run News Ticker

on:
  workflow_dispatch: {}           # manueller Start-Button
  schedule:
    - cron: "5,35 * * * *"        # alle 30 Min (UTC) – anpassbar

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ticker
        env:
          FETCH_MODE: "DELTA"     # für Tests ggf. "WINDOW"
        run: |
          python news.py

      - name: Commit JSON back to repo
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update news_delta.json [skip ci]" || echo "No changes"
          git push
